version: "3.3"

services:
  mongo:
    image: mongo:4
    volumes:
      - data:/data/db
    ports:
      - "27017:27017"
    networks:
      - internal

  nats:
    image: nats:2
    networks:
      - internal
  redis:
    image: redis:alpine
    networks:
      - internal

networks:
  internal:

volumes:
  data:
